#!/usr/bin/env python3
"""
RPZ (Response Policy Zone) Manager Module
Manages DNS Response Policy Zones for blocking malicious domains
"""

import os
import logging
import json
import subprocess
import tempfile
from datetime import datetime, timedelta
from typing import List, Dict, Set, Optional, Tuple
from dataclasses import dataclass

@dataclass
class BlockedDomain:
    """Information about a blocked domain"""
    domain: str
    timestamp: datetime
    reason: str
    policy: str = "CNAME ."
    ttl: int = 300
    auto_unblock_time: Optional[datetime] = None

class RPZManager:
    def __init__(self, config: Dict):
        self.config = config
        self.logger = logging.getLogger(__name__)
        self.rpz_file = config.get('rpz_file', '/etc/bind/db.rpz')
        self.blocked_domains = {}  # domain -> BlockedDomain
        self.zone_name = "rpz.local"
        
        # RPZ policy options
        self.policies = {
            'nxdomain': 'CNAME .',
            'nodata': 'CNAME *.',
            'passthru': 'CNAME rpz-passthru.',
            'drop': 'CNAME rpz-drop.',
            'tcp_only': 'CNAME rpz-tcp-only.',
            'redirect': 'A 127.0.0.1'  # Can be customized
        }
        
        # Load existing blocked domains
        self._load_blocked_domains()
        
    def _load_blocked_domains(self):
        """Load blocked domains from RPZ file"""
        if not os.path.exists(self.rpz_file):
            self.logger.warning(f"RPZ file not found: {self.rpz_file}")
            return
            
        try:
            with open(self.rpz_file, 'r') as f:
                content = f.read()
                
            # Parse RPZ entries (simplified parser)
            for line in content.split('\n'):
                line = line.strip()
                if line and not line.startswith(';') and not line.startswith('$'):
                    # Look for domain entries
                    if 'CNAME' in line or 'A ' in line:
                        parts = line.split()
                        if len(parts) >= 3:
                            domain = parts[0].rstrip('.')
                            if domain and domain != self.zone_name:
                                # Extract policy
                                policy_parts = parts[2:]
                                policy = ' '.join(policy_parts)
                                
                                self.blocked_domains[domain] = BlockedDomain(
                                    domain=domain,
                                    timestamp=datetime.now(),
                                    reason="Loaded from RPZ file",
                                    policy=policy
                                )
                                
            self.logger.info(f"Loaded {len(self.blocked_domains)} domains from RPZ file")
            
        except Exception as e:
            self.logger.error(f"Error loading RPZ file: {e}")
            
    def _generate_rpz_header(self) -> str:
        """Generate RPZ zone file header"""
        timestamp = datetime.now().strftime('%Y%m%d%H%M%S')
        
        header = f"""; RPZ Zone File - Auto-generated by DNS DDoS Monitor
; Generated: {datetime.now().isoformat()}
; 
$TTL 300
$ORIGIN {self.zone_name}.

@   IN  SOA localhost. admin.localhost. (
        {timestamp}01  ; Serial (timestamp + counter)
        3600           ; Refresh
        1800           ; Retry
        604800         ; Expire
        300            ; Minimum TTL
    )
    IN  NS  localhost.

; Policy entries below
"""
        return header
        
    def _write_rpz_file(self) -> bool:
        """Write current blocked domains to RPZ file"""
        try:
            # Create backup of existing file
            if os.path.exists(self.rpz_file):
                backup_file = f"{self.rpz_file}.backup.{int(datetime.now().timestamp())}"
                subprocess.run(['cp', self.rpz_file, backup_file], check=True)
                
            # Generate new RPZ content
            content = self._generate_rpz_header()
            
            # Add blocked domains
            for domain, blocked_domain in self.blocked_domains.items():
                # Format domain for RPZ (ensure it ends with zone name)
                rpz_domain = f"{domain}.{self.zone_name}."
                content += f"{rpz_domain}\tIN\t{blocked_domain.policy}\t; {blocked_domain.reason}\n"
                
            # Write to temporary file first
            with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.rpz') as temp_file:
                temp_file.write(content)
                temp_path = temp_file.name
                
            # Move temporary file to final location
            subprocess.run(['mv', temp_path, self.rpz_file], check=True)
            
            # Set appropriate permissions
            subprocess.run(['chmod', '644', self.rpz_file], check=True)
            
            self.logger.info(f"Updated RPZ file with {len(self.blocked_domains)} domains")
            
            return True
            
        except Exception as e:
            self.logger.error(f"Error writing RPZ file: {e}")
            return False
            
    def _reload_bind(self) -> bool:
        """Reload BIND9 to apply RPZ changes"""
        try:
            # Try multiple reload methods
            reload_commands = [
                ['systemctl', 'reload', 'bind9'],
                ['systemctl', 'reload', 'named'],
                ['service', 'bind9', 'reload'],
                ['service', 'named', 'reload'],
                ['rndc', 'reload']
            ]
            
            for cmd in reload_commands:
                try:
                    result = subprocess.run(cmd, capture_output=True, text=True, check=True)
                    self.logger.info(f"BIND9 reloaded successfully using: {' '.join(cmd)}")
                    return True
                except subprocess.CalledProcessError:
                    continue
                    
            self.logger.error("Failed to reload BIND9 with any method")
            return False
            
        except Exception as e:
            self.logger.error(f"Error reloading BIND9: {e}")
            return False
            
    def block_domain(self, domain: str, reason: str = "DGA detected", 
                    policy: str = "nxdomain", ttl: int = 300,
                    duration_hours: Optional[int] = None) -> bool:
        """Block a domain using RPZ"""
        
        # Normalize domain
        domain = domain.lower().rstrip('.')
        
        # Skip if already blocked
        if domain in self.blocked_domains:
            self.logger.info(f"Domain {domain} is already blocked")
            return True
            
        # Validate policy
        if policy not in self.policies:
            self.logger.error(f"Invalid policy: {policy}. Available: {list(self.policies.keys())}")
            return False
            
        try:
            # Calculate auto-unblock time if duration specified
            auto_unblock_time = None
            if duration_hours:
                auto_unblock_time = datetime.now() + timedelta(hours=duration_hours)
                
            # Create blocked domain entry
            blocked_domain = BlockedDomain(
                domain=domain,
                timestamp=datetime.now(),
                reason=reason,
                policy=self.policies[policy],
                ttl=ttl,
                auto_unblock_time=auto_unblock_time
            )
            
            # Add to tracking
            self.blocked_domains[domain] = blocked_domain
            
            # Update RPZ file
            if self._write_rpz_file():
                # Reload BIND9
                if self._reload_bind():
                    self.logger.warning(f"Blocked domain {domain} via RPZ: {reason}")
                    self._log_blocked_domain(blocked_domain)
                    return True
                else:
                    # Rollback if reload failed
                    del self.blocked_domains[domain]
                    self.logger.error(f"Failed to reload BIND9 after blocking {domain}")
                    return False
            else:
                # Rollback if file write failed
                del self.blocked_domains[domain]
                return False
                
        except Exception as e:
            self.logger.error(f"Error blocking domain {domain}: {e}")
            return False
            
    def unblock_domain(self, domain: str, reason: str = "Manual unblock") -> bool:
        """Unblock a domain by removing from RPZ"""
        
        domain = domain.lower().rstrip('.')
        
        if domain not in self.blocked_domains:
            self.logger.info(f"Domain {domain} is not currently blocked")
            return True
            
        try:
            # Remove from tracking
            del self.blocked_domains[domain]
            
            # Update RPZ file
            if self._write_rpz_file():
                # Reload BIND9
                if self._reload_bind():
                    self.logger.info(f"Unblocked domain {domain}: {reason}")
                    return True
                else:
                    self.logger.error(f"Failed to reload BIND9 after unblocking {domain}")
                    return False
            else:
                return False
                
        except Exception as e:
            self.logger.error(f"Error unblocking domain {domain}: {e}")
            return False
            
    def block_multiple_domains(self, domains: List[str], reason: str = "Bulk DGA block",
                              policy: str = "nxdomain") -> Dict[str, bool]:
        """Block multiple domains at once"""
        results = {}
        
        # Add all domains to tracking first
        added_domains = []
        for domain in domains:
            domain = domain.lower().rstrip('.')
            if domain not in self.blocked_domains:
                blocked_domain = BlockedDomain(
                    domain=domain,
                    timestamp=datetime.now(),
                    reason=reason,
                    policy=self.policies.get(policy, self.policies['nxdomain'])
                )
                self.blocked_domains[domain] = blocked_domain
                added_domains.append(domain)
                results[domain] = False  # Will update to True if successful
                
        if added_domains:
            # Update RPZ file once
            if self._write_rpz_file() and self._reload_bind():
                # Mark all as successful
                for domain in added_domains:
                    results[domain] = True
                    self._log_blocked_domain(self.blocked_domains[domain])
                    
                blocked_count = len(added_domains)
                self.logger.warning(f"Blocked {blocked_count} domains via RPZ: {reason}")
            else:
                # Rollback all additions
                for domain in added_domains:
                    if domain in self.blocked_domains:
                        del self.blocked_domains[domain]
                        
        return results
        
    def get_blocked_domains(self) -> Dict[str, BlockedDomain]:
        """Get all currently blocked domains"""
        return self.blocked_domains.copy()
        
    def cleanup_expired_blocks(self) -> int:
        """Remove expired auto-unblock domains"""
        current_time = datetime.now()
        expired_domains = []
        
        for domain, blocked_domain in self.blocked_domains.items():
            if (blocked_domain.auto_unblock_time and 
                current_time >= blocked_domain.auto_unblock_time):
                expired_domains.append(domain)
                
        # Unblock expired domains
        if expired_domains:
            for domain in expired_domains:
                del self.blocked_domains[domain]
                
            # Update RPZ file once
            if self._write_rpz_file() and self._reload_bind():
                self.logger.info(f"Auto-unblocked {len(expired_domains)} expired domains")
            else:
                self.logger.error("Failed to update RPZ after auto-unblock")
                
        return len(expired_domains)
        
    def _log_blocked_domain(self, blocked_domain: BlockedDomain):
        """Log blocked domain to alerts log"""
        try:
            alerts_file = self.config.get('alerts_log', 'data/alerts_log.json')
            
            log_entry = {
                'timestamp': blocked_domain.timestamp.isoformat(),
                'type': 'domain_block',
                'domain': blocked_domain.domain,
                'reason': blocked_domain.reason,
                'policy': blocked_domain.policy,
                'auto_unblock_time': blocked_domain.auto_unblock_time.isoformat() 
                                   if blocked_domain.auto_unblock_time else None
            }
            
            # Append to alerts log
            if os.path.exists(alerts_file):
                with open(alerts_file, 'r') as f:
                    alerts = json.load(f)
            else:
                alerts = []
                
            alerts.append(log_entry)
            
            with open(alerts_file, 'w') as f:
                json.dump(alerts, f, indent=2)
                
        except Exception as e:
            self.logger.error(f"Error logging blocked domain: {e}")
            
    def get_rpz_stats(self) -> Dict:
        """Get RPZ statistics"""
        current_time = datetime.now()
        
        # Count blocks by time periods
        last_hour = current_time - timedelta(hours=1)
        last_day = current_time - timedelta(days=1)
        
        recent_blocks_hour = sum(1 for blocked_domain in self.blocked_domains.values() 
                                if blocked_domain.timestamp >= last_hour)
        recent_blocks_day = sum(1 for blocked_domain in self.blocked_domains.values() 
                               if blocked_domain.timestamp >= last_day)
        
        # Count auto-unblock scheduled
        auto_unblock_count = sum(1 for blocked_domain in self.blocked_domains.values() 
                                if blocked_domain.auto_unblock_time)
        
        # Policy distribution
        policy_counts = {}
        for blocked_domain in self.blocked_domains.values():
            policy = blocked_domain.policy
            policy_counts[policy] = policy_counts.get(policy, 0) + 1
            
        stats = {
            'total_blocked_domains': len(self.blocked_domains),
            'blocks_last_hour': recent_blocks_hour,
            'blocks_last_day': recent_blocks_day,
            'auto_unblock_scheduled': auto_unblock_count,
            'policy_distribution': policy_counts,
            'rpz_file': self.rpz_file,
            'zone_name': self.zone_name
        }
        
        return stats
        
    def export_blocked_domains(self, format: str = 'json') -> str:
        """Export blocked domains in specified format"""
        if format.lower() == 'json':
            export_data = []
            for domain, blocked_domain in self.blocked_domains.items():
                export_data.append({
                    'domain': blocked_domain.domain,
                    'timestamp': blocked_domain.timestamp.isoformat(),
                    'reason': blocked_domain.reason,
                    'policy': blocked_domain.policy,
                    'ttl': blocked_domain.ttl,
                    'auto_unblock_time': blocked_domain.auto_unblock_time.isoformat() 
                                       if blocked_domain.auto_unblock_time else None
                })
            return json.dumps(export_data, indent=2)
            
        elif format.lower() == 'csv':
            lines = ['Domain,Timestamp,Reason,Policy,TTL,Auto_Unblock_Time']
            for domain, blocked_domain in self.blocked_domains.items():
                auto_unblock_str = blocked_domain.auto_unblock_time.isoformat() if blocked_domain.auto_unblock_time else ''
                lines.append(f"{blocked_domain.domain},{blocked_domain.timestamp.isoformat()},{blocked_domain.reason},{blocked_domain.policy},{blocked_domain.ttl},{auto_unblock_str}")
            return '\n'.join(lines)
            
        else:
            raise ValueError(f"Unsupported export format: {format}")
            
    def test_rpz_configuration(self) -> Dict[str, bool]:
        """Test RPZ configuration"""
        tests = {}
        
        # Test file permissions
        tests['rpz_file_exists'] = os.path.exists(self.rpz_file)
        tests['rpz_file_readable'] = os.access(self.rpz_file, os.R_OK) if tests['rpz_file_exists'] else False
        tests['rpz_file_writable'] = os.access(self.rpz_file, os.W_OK) if tests['rpz_file_exists'] else False
        
        # Test BIND9 availability
        try:
            result = subprocess.run(['named', '-v'], capture_output=True, text=True)
            tests['bind9_available'] = result.returncode == 0
        except FileNotFoundError:
            tests['bind9_available'] = False
            
        # Test rndc availability
        try:
            result = subprocess.run(['rndc', 'status'], capture_output=True, text=True)
            tests['rndc_available'] = result.returncode == 0
        except FileNotFoundError:
            tests['rndc_available'] = False
            
        return tests